---
title: "brexit app"
resource_files:
- england_wales.cpg
- england_wales.dbf
- england_wales.prj
- england_wales.qpj
- england_wales.shp
- england_wales.shx
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: https://github.com/cat-lord/shinyapps/tree/master/brexit
    theme: yeti
---

```{r setup, include=FALSE}

library(flexdashboard) ; library(rgdal) ; library(sp) ; library(dplyr) ; library(shiny) ; library(leaflet) ; library(RColorBrewer) ; library(plotly) ; library(ggplot2) ; library(formattable)

boundaries <- readOGR("england_wales.geojson", "OGRGeoJSON", verbose = FALSE)

df <- data.frame(Area = c("England & Wales", ""),
        Region = c("",""), 
        Electorate = c("41,227,815", ""),
        Leave = c(round(sum(boundaries$Leave) / sum(boundaries$Vts_Cst) * 100, 1), ""),
        Remain = c(round(sum(boundaries$Remain) / sum(boundaries$Vts_Cst) * 100, 1), ""),
        Turnout = c(round(sum(boundaries$Vts_Cst) / sum(boundaries$Electrt) * 100, 1), ""),
        Result = c("Leave", "")) %>% 
  rename(`Leave (%)` = Leave, `Remain (%)` = Remain, `Turnout (%)` = Turnout)
```

Inputs {.sidebar data-width=400 data-padding=10}
-------------------------------------

<br>

This app is designed to allow users to explore the relationship between levels of immigration - measured as the percentage of residents born outside the UK -  and the results of the EU referendum on 23 June 2016.   

**Instructions**   
Use the lasso tool on the scatterplot to render corresponding local authorities on the map. Then click an area to reveal the referendum results for that specific local authority in the table at the bottom of the screen.   

**Credits**   
This app was inspired by an article in [theconversation.com](http://theconversation.com/uk) called ['Hard Evidence: how areas with low immigration voted mainly for Brexit'](http://theconversation.com/hard-evidence-how-areas-with-low-immigration-voted-mainly-for-brexit-62138) and by Kyle Walker's Shiny [app on neighborhood diversity](https://github.com/walkerke/neighborhood_diversity).   

**Data sources**

- [EU referendum results](http://www.electoralcommission.org.uk/__data/assets/file/0014/212135/EU-referendum-result-data.csv)
- [Population data from the 2011 Census](http://www.ons.gov.uk/ons/rel/census/2011-census/key-statistics-for-unitary-authorities-in-wales/rft-table-ks204ew.xls)
- [Boundary layers](https://geoportal.statistics.gov.uk/geoportal/catalog/content/filelist.page?&pos=3&cat=#BD)


Row  {data-height=800}
-----------------------------------------------------------------------
###

```{r}

# Here, we draw the diversity gradient with ggplotly
output$scatter <- renderPlotly({
  
  key <- boundaries$Area_Cd 
  
  plot <- ggplot(boundaries@data) + 
  geom_point(alpha = 0.4, aes(Non.UK, Pct_Lev, key = key)) + 
  theme_minimal() + 
  stat_smooth(aes(Non.UK, Pct_Lev), color = '#045a8d', method = 'loess', se = FALSE) +  
  geom_vline(xintercept = 13.3, colour = '#045a8d') + geom_hline(yintercept = 50, colour = '#045a8d') +
  xlab('% of non-UK born residents (2011 Census)') + 
  ylab('% of Leave votes') 
    
  g <- ggplotly(plot, source = 'source') %>% 
    layout(dragmode = 'lasso', 
           margin = list(l = 100), 
           font = list(family = 'Arial', size = 12))
  
  # Need to manually set the hoverinfo to avoid the key appearing in it
  build <- plotly_build(g)
  
  build$data[[1]]$text <- paste0('Local authority: ', as.character(boundaries$Area),'<br>',
    'Leave votes (%): ', as.character(round(boundaries$Pct_Lev, 1)), '<br>', 
                               'non-UK residents (%): ', as.character(round(boundaries$Non.UK, 1))) 

  build
    
})  

plotlyOutput('scatter')
```

###

```{r}

sub <- reactive({
    eventdata <- event_data('plotly_selected', source = 'source')
    if (is.null(eventdata)) {
      return(NULL)
    } else {
      areas <- eventdata[['key']]
      if (length(areas) == 0) {
        areas <- 'nowhere'
      }
      if (!(areas %in% boundaries$Area_Cd)) {
        return(NULL)
      } else {
        sub <- boundaries[boundaries$Area_Cd %in% areas, ]
        return(sub)
      }
    }
  })


output$map <- renderLeaflet({
  
  pal <- colorFactor(c("#80b1d3", "#ffffb3"), domain = c("Leave", "Remain"))
  
  if(is.null(sub())) {leaflet() %>% 
      addProviderTiles('CartoDB.Positron') %>%
      addPolygons(data = boundaries, color = "#969696", weight = 1,
                  fillColor = ~pal(Result), fillOpacity = 0.5, layerId = ~Area_Cd) %>%
        addLegend(position = "topright", colors = c("#ffffb3", "#80b1d3"),
labels = c("Majority Remain", "Majority Leave"), opacity = 1)} 
  else {
    leaflet(data = sub() ) %>%
    addProviderTiles('CartoDB.Positron') %>%
    addPolygons(data = boundaries, color = "#969696", weight = 1,
                  fillColor = ~pal(Result), fillOpacity = 0.5, layerId = ~Area_Cd) %>% 
    addPolygons(data = sub(), stroke = TRUE, color = '#525252', opacity = 1, weight = 1,
                fillColor = "white", fillOpacity = 1,
                layerId = ~Area_Cd)  %>%
    fitBounds(lng1 = bbox(sub())[1],
              lat1 = bbox(sub())[2],
              lng2 = bbox(sub())[3],
              lat2 = bbox(sub())[4])  %>%
      addLegend(position = "topright", colors = c("#ffffb3", "#80b1d3"),
                labels = c("Majority Remain", "Majority Leave"), opacity = 1)
    }
  })

click_area <- eventReactive(input$map_shape_click, {
    x <- input$map_shape_click
    y <- x$id
    return(y)
  })

observe({
  
  req(click_area())

  map <- leafletProxy('map') %>%
      removeShape('highlighted') %>%
      addPolygons(data = boundaries[boundaries$Area_Cd == click_area(), ], fill = FALSE,
                  color = 'red', opacity = 1, layerId = 'highlighted')

  })

click_area_data <- reactive({
    return(boundaries@data[boundaries@data$Area_Cd == click_area(), ]) %>% 
    select(Area, Region, 
           Electorate = Electrt,
           `Leave (%)` = Pct_Lev,
           `Remain (%)` = Pct_Rmn,
           `Turnout (%)` = Pct_Trn,
           Result) %>% 
     mutate(Electorate = format(Electorate, big.mark=",", scientific=FALSE),
       `Leave (%)` = round(`Leave (%)`, 1), 
            `Remain (%)` = round(`Remain (%)`, 1), 
            `Turnout (%)` = round(`Turnout (%)`, 1))
  })

leafletOutput('map')  
```

Row   {data-height=80}
-----------------------------------------------------------------------

###
 
```{r}
output$table <- renderFormattable({
 if(is.null(input$map_shape_click)) {
    formattable(df[1,])
  } else{
    formattable(click_area_data())
  }

})

formattableOutput('table')
```
